#Use the official Python image from the Docker hub
FROM python:3.9-slim

#Settheworking  directory 
WORKDIR /app

#Copy the current directory contents into the container at /app
COPY ./app

#Intall any needed packages requireed
RUN pip install flask

#Make port 5000  available to the world outside this container
EXPOSE 5000

#Run app.py when the container launches
CMD ["python" , "app.py"]